### ISSUE TITLE
[FE] 그래프 튜닝

### ISSUE THREAD

**Issue by SeryeongK** [insight-LINK/insightLINK#11]
# ✅ FEATURE
그래프 튜닝

## ❗️ Todo
- [x] 다중 연결 확인
- [x] 그래프 제목 변경
- [x] 옵션 수정(edge 스타일, 노드 간 거리)
- [x] 자동으로 좌표 그리기

## 📸 스크린샷
<img width="960" alt="image" src="https://github.com/insight-LINK/insightLINK/assets/67596636/28eefa90-d29e-4db8-ac41-4c74586e5d2a">
