### ISSUE TITLE
[QA] 검색기능

### ISSUE THREAD

**Issue by godee95** [insight-LINK/insightLINK#128]
# ✅ FEATURE
검색기능 QA

## ❗️ Todo
- [x] 검색결과 나온 갯수&더보기 카드 갯수 일치
- [x] 이전페이지 있을 경우에만 이전페이지 버튼 노출
- [x] 다음페이지 있을 경우에만 다음페이지 버튼 노출
- [ ] 서버 죽는 문제

## 📸 스크린샷
![검색 버튼수정](https://github.com/insight-LINK/insightLINK/assets/50854903/39a1322b-bf8a-423c-8228-647f23b28c24)
