### ISSUE TITLE
[FE] 소셜 페이지

### ISSUE THREAD

**Issue by SeryeongK** [insight-LINK/insightLINK#3]
# ✅ FEATURE
소셜 페이지

## ❗️ Todo
- [x] 레이아웃
- [x] 추천 카드 조회
- [x] 추천 친구 레이아웃 추가
- [x] 최근 업데이트 친구 조회
- [x] 최근 업데이트 친구 조회 API 연결
- [x] 추천 카드 조회 API 연결
- [x] 추천 친구 조회 API 연결
- [x] 팔로잉 등록/취소
- [x] 상세 페이지
- [x] 팔로잉 피드와 추천 피드 구분
- [x] 내 그래프에 다른 사람의 카드 추가 API 연결
- [x] 디자인 수정
- [x] Onboarding 페이지 추가
- [ ] Code Spliting

## 📸 스크린샷
<img width="1892" alt="image" src="https://github.com/insight-LINK/insightLINK/assets/67596636/7d273dd3-aac3-4cd5-b9cd-d2cd59569559">

<img width="1906" alt="image" src="https://github.com/insight-LINK/insightLINK/assets/67596636/5bc52c46-4fcf-4026-b857-21e31ccdd0ae">

<img width="933" alt="image" src="https://github.com/insight-LINK/insightLINK/assets/67596636/7f40cff8-06f5-4cdc-9d1f-bb50d5bd1f11">

<img width="1109" alt="image" src="https://github.com/insight-LINK/insightLINK/assets/67596636/9d0324f8-91d3-4b6e-aa02-2bab8e9f4679">
