### ISSUE TITLE
[FE] 태그 병합

### ISSUE THREAD

**Issue by SeryeongK** [insight-LINK/insightLINK#38]
# ✅ FEATURE
태그 병합

## ❗️ Todo
- [x] 폴더 구조 변경
- [x] 태그 병합 함수 구현
- [ ] 태그 병합 컴포넌트화
- [ ] 태그 병합 인터랙션
